### ISSUE TITLE
Yolo models for breast cancer research

### ISSUE THREAD

**Issue by blazespinnaker** [AsmaBaccouche/Early-Detection-and-Classification-of-Breast-Cancer#1]
Dear Maam,

I am trying to contribute in an open source manner to breast cancer detection research.  I've noticed quite a few papers in the last year or so are using Yolo models.  I was hoping that by ensembling them I'd be able to make a compelling contribution to the field and help solve a very important health problem - early detection of breast cancer.   

I noticed you've done some research in this field.  Would you have made your yolo models available?   I don't need any further documentation or assistance, just looking for the underlying pytorch model and version it was trained under.  

I will be sure to carefully cite and give credit to all folks who contribute to this effort.

Thank you very much for any help you can on this effort!

**Comment by AsmaBaccouche** [comment]
Hi,

Thanks for reaching out. The YOLO model is YoloV3 and written in Keras/Tensorflow, inspired by this [Github repo](https://github.com/qqwweee/keras-yolo3)

Also, check my [Paper](https://www.techscience.com/cmc/v69n1/42797) where I discussed more the use case for breast cancer.

Thanks,

**Comment by blazespinnaker** [comment]
Thanks.  Would it be possible to make the yolo model weights available for download?

**Comment by AsmaBaccouche** [comment]
https://pjreddie.com/darknet/yolo/

**Comment by blazespinnaker** [comment]
These haven't been trained on breast cancer data.   Here's an example of something that has - 
https://www.kaggle.com/datasets/vbookshelf/mammogram-mass-analyzer-v00

look in the mammogram-mass-analyzer-v0.0/yolov5/TRAINED_MODEL_FOLDER directory  and you'll see two pytorch models specifically trained on data from https://physionet.org/content/vindr-mammo/1.0.0/
